# Generated by Django 2.2.6 on 2020-04-15 00:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('comment', models.TextField(max_length=120)),
                ('users', models.ManyToManyField(blank=True, related_name='agents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
