# Generated by Django 2.2.6 on 2019-10-22 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=32)),
                ('totalparts', models.IntegerField()),
                ('sessionhash', models.CharField(max_length=32)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=1)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Agent')),
            ],
        ),
        migrations.CreateModel(
            name='UploadPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=32)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('data', models.FileField(upload_to='uploads')),
                ('complete', models.BooleanField(default=False)),
                ('valid', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packageparts', to='storage.UploadSession')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=32)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('data', models.FileField(upload_to='storage')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Agent')),
            ],
        ),
    ]
