# Generated by Django 2.2.6 on 2020-04-15 00:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupRoot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=4096)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Agent')),
            ],
        ),
        migrations.CreateModel(
            name='BackupSnapshot',
            fields=[
                ('timestamp', models.DateTimeField(auto_created=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seqno', models.IntegerField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Agent')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storage.BackupSnapshot')),
                ('root', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.BackupRoot')),
            ],
        ),
        migrations.CreateModel(
            name='DbFile',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('data', models.FileField(max_length=255, upload_to='storage')),
                ('valid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('expectedparts', models.IntegerField()),
                ('receivedparts', models.IntegerField(default=0)),
                ('fullhash', models.CharField(max_length=64)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='N', max_length=1)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Agent')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session', to='storage.DbFile')),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('objhash', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=4096)),
                ('type', models.CharField(max_length=4)),
                ('stat', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='storage.Object')),
                ('prime', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storage.DbFile')),
                ('snapshots', models.ManyToManyField(null=True, related_name='backup_objects', to='storage.BackupSnapshot')),
            ],
        ),
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=4096)),
                ('stat', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_dirs', to='storage.Directory')),
            ],
        ),
    ]
