# Generated by Django 2.2.6 on 2020-04-22 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='storage.Object'),
        ),
        migrations.AlterField(
            model_name='object',
            name='snapshots',
            field=models.ManyToManyField(related_name='backup_objects', to='storage.BackupSnapshot'),
        ),
    ]
